language: php

php:
  - 5.3

before_script:
  - mkdir Build; cd Build
  # Test this
  - |
    cat <<EOF > composer.json
    {
        "name": "typo3/flow-base-distribution",
        "config": {
            "vendor-dir": "Packages/Libraries",
            "bin-dir": "bin"
        },
        "require": {
            "flowpack/singlesignon-client": "dev-${TRAVIS_BRANCH}#${TRAVIS_COMMIT}"
        },
        "require-dev": {
            "typo3/buildessentials": "dev-master",
            "mikey179/vfsstream": "1.1.*"
        },
        "minimum-stability": "dev",
        "scripts": {
            "post-update-cmd": "TYPO3\\\\Flow\\\\Composer\\\\InstallerScripts::postUpdateAndInstall",
            "post-install-cmd": "TYPO3\\\\Flow\\\\Composer\\\\InstallerScripts::postUpdateAndInstall"
        }
    }
    EOF
  - composer update --dev

script: phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/Networkteam.Tika/Tests/Functional
